name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DHPRP_ENABLE_SANITIZERS=ON
      - name: Build
        run: cmake --build build -j2
      - name: Test
        run: ctest --test-dir build --output-on-failure --verbose
